from src.core.routing_models import IntentType

# Patrones por intent type
INTENT_PATTERNS = {
    IntentType.FILE_ANALYSIS: [
        "archivo",
        "documento",
        "pdf",
        "analizar",
        "revisar",
        "examinar",
        "procesar",
        "leer",
        "extraer",
    ],
    IntentType.PLANNING: [
        "planificar",
        "cronograma",
        "organizar",
        "planear",
        "programar",
        "itinerario",
        "agenda",
        "calendario",
    ],
    IntentType.SEARCH: [
        "buscar",
        "encontrar",
        "información sobre",
        "dime sobre",
        "investiga",
        "consulta",
        "averigua",
        "explora",
    ],
    IntentType.HELP: [
        "ayuda",
        "cómo",
        "explicar",
        "tutorial",
        "guía",
        "instrucciones",
        "asistencia",
        "apoyo",
    ],
    IntentType.VULNERABILITY: {
        "positive_patterns": [
            # === 1. Emociones negativas básicas ===
            "miedo",
            "tristeza",
            "ira",
            "asco",
            "ansiedad",
            "angustia",
            # === Emociones secundarias ===
            "soledad",
            "desesperación",
            "culpabilidad",
            "vergüenza",
            "frustración",
            "envidia",
            "agobio",
            "apatía",
            # === 2. Distorsiones cognitivas TCC ===
            "todo o nada",
            "siempre me pasa",
            "nunca logro",
            "fracaso total",
            "todos me",
            "nadie me",
            "nunca funciona",
            "lo peor",
            "terrible",
            "desastre",
            "catástrofe",
            "es mi culpa",
            "por mi culpa",
            "piensan que",
            "me juzgan",
            # === 3. Pensamientos automáticos negativos ===
            "no soy suficiente",
            "no sirvo para",
            "soy un fracaso",
            "nadie me quiere",
            "estoy solo",
            "estoy sola",
            "no lo lograré",
            "no tiene sentido",
            # === 4. Solicitudes de ayuda ===
            "necesito ayuda",
            "ayúdame",
            "no sé qué hacer",
            "necesito desahogarme",
            "quiero hablar",
            # === 5. Síntomas específicos ===
            "muy nervioso",
            "muy nerviosa",
            "estresado",
            "estresada",
            "pánico",
            "sin energía",
            "desmotivado",
            "desmotivada",
            "me siento vacío",
            "me siento vacía",
            "no me valoro",
            "no me acepto",
            # === 6. Triggers contextuales ===
            "cuando me pasa",
            "cada vez que",
            "me ocurre que",
            # === Frases originales mejoradas ===
            "me siento mal",
            "estoy agotado",
            "estoy deprimido",
            "agotado",
            "triste",
            "deprimido",
            "mal",
            "siento",
        ],
        "negative_patterns": [
            # Excluir contextos de trading/técnicos
            "el trade",
            "la operación",
            "el mercado",
            "la bolsa",
            "stop loss",
            "take profit",
            "análisis técnico",
        ],
    },
    IntentType.TOPIC_SHIFT: [
        "deja",
        "basta",
        "para con",
        "otro tema",
        "cambia",
        "olvida",
        "no quiero hablar de",
        "suficiente de",
    ],
}
